stages:
  - code-quality
  - test

EsLint & Rubocop:
  stage: code-quality
  tags:
    - ci
    - ssh
  before_script:
    - ruby -v
    - node -v
    - gem install rubocop -v 0.79.0 --no-document
    - gem install rubocop-performance -v 1.5.2 --no-document
    - yarn install --frozen-lockfile --offline --check-files
    - git fetch origin main
  script:
    - echo 'Rubocop task'

MiniTest:
  stage: test
  tags:
    - ci
    - ssh
  services:
    - name: ubuntu/mysql:latest
      alias: mysql
  script:
    - echo 'Minitest task'

ClientIntegrationtest:
  stage: test
  tags:
    - ci
    - ssh
  services:
    - name: ubuntu/mysql:latest
      alias: mysql
  script:
    - yarn install --frozen-lockfile --production --offline
    - bin/rake assets:precompile
    - bin/rails test test/integration/client

AdminIntegrationtest:
  stage: test
  tags:
    - ci
  services:
    - name: ubuntu/mysql:latest
      alias: mysql
  script:
    - yarn install --frozen-lockfile --production --offline
    - bin/rake assets:precompile
    - bin/rails test test/integration/admin
